### ISSUE TITLE
Make some private bots optional

### ISSUE THREAD

**Issue by mgwalker** [18F/charlie#264]
[Slack thread](https://gsa-tts.slack.com/archives/C0XUF8XL1/p1611353543042300)

It would be nice if users could turn off Happy Tock and Tiny Tau Bot, for example.

**Comment by lauraGgit** [comment]
🙇‍♀️

**Comment by mgwalker** [comment]
Closed by #271. You can now opt out of Baby Tock by clicking the little dots thingy, hopefully.
