### ISSUE TITLE
Timebot does not support 24 hour time

### ISSUE THREAD

**Issue by jduss4** [18F/charlie#292]
~Currently the timebot does not return correct time zone responses if a 24 hour time is passed in.~ Currently timebot does not accommodate "pm" when 24 hour time is passed in.

Do we want it to support 24 hour time?  If so, should it return 12 hour time (+ "pm" if relevant) or return 24 hour time?

Relevant to https://github.com/18F/charlie/commit/b15b26884e0ac7320e03f3b9866a84249b3a6353

**Comment by mgwalker** [comment]
For simplicity, I would suggest that if the user-entered time is >= 13:00, we show the result with am/pm text always. That should do for now?

**Comment by mgwalker** [comment]
I believe this is resolved?

![image](https://user-images.githubusercontent.com/1775733/169338012-18d9c419-0bdd-450d-84f8-ebec6f70dc09.png)
