### ISSUE TITLE
Inclusion bot: Don't trigger on emoji

### ISSUE THREAD

**Issue by mgwalker** [18F/charlie#315]
The process for approving/renaming/removing emoji is distinct from the Inclusion Bot. If an emoji is approved, users should not be notified for using it.

E.g., `:am-i-crazy:`

If the emoji should be removed or renamed, that should be taken up elsewhere.

**Comment by loganmeetsworld** [comment]
Are you already working on this one? If not I might take a look. Regex wrangling might be a fun puzzle for me today 😄

**Comment by mgwalker** [comment]
It's yours! I'm working on updating my personal readme this morning. 😄

**Comment by cmajel** [comment]
👋🏻  I was kind of happy to see that the inclusion bot was flagging an emoji alias, since that is also a method of communication in slack as much as a typed message. 

Is there some sort of check during the custom emoji process for this? I wonder how this gets flagged in the future if we remove it.

**Comment by mgwalker** [comment]
We could have the bot periodically pull a list of all emoji, check them against the Inclusion Bot's word/phrase list, and report that somewhere? We could even do that *now* to find any problematic emoji names that already exist. For now, when new emoji are created, they go must be manually approved and the [approval criteria](https://handbook.tts.gsa.gov/tools/slack/user-management/#approval-criteria) specifically refers to ensuring that they are in line with our diversity and inclusion values. But I agree this is a good thing to talk about before we implement this.

Ping @adborden: I think you've thought about longer-term solutions for emoji approvals, and it might be possible to loop the Inclusion Bot into that process as a first check on emoji names and stuff at some point.

**Comment by adborden** [comment]
A preliminary check to aide emoji admins sounds like a good idea. If you feel like you're close to having a working implementation, open an issue in [18F/tts-tech-portfolio](https://github.com/18F/tts-tech-portfolio/issues/new?assignees=&labels=g%3A+initial&template=general.md&title=) so we can integrate it with the process.

**Comment by mgwalker** [comment]
Here are the emoji that currently trigger a bot response:

```
:am-i-crazy:
:derp:
:ninja-moves:
:russ-maniac:
:russ-maniac-2:
:taking-crazy-pills:
```

- `:am-i-crazy:` is an alias for `:samelook:`. I appreciate the intent of this emoji, and would invite a discussion about how we use the word "crazy." Maybe a good topic for [#processing-privilege](https://app.slack.com/client/T025AQGAN/C02250C7H2P)? I'm really at a loss for a better way to express the feeling that this emoji and its name conveys.
- `:taking-crazy-pills:` is also an alias for `:samelook:`. Judging from how it's used in Slack, it's used interchangeably with `:am-i-crazy:`. Maybe part of the same conversation ☝🏻 as above?
- `:ninja-moves:` is an animation of an actual ninja. I think it's probably fine since it's not misusing the term? I would probably vote that we add this one in particular as an exception to the bot.
- `:russ-maniac:` and `:russ-maniac-2:` are both references to a person who is no longer at TTS, and I think it would be safe to deprecate those.

**Comment by mgwalker** [comment]
@adborden https://github.com/18F/tts-tech-portfolio/issues/1522

**Comment by mgwalker** [comment]
I think we've informally decided not to do this. At this moment, only the standard Unicode 🥷 emoji should trigger the bot, but having the bot continue to check emoji can act as an extra backstop for emoji approval.
