### ISSUE TITLE
Document the process of updating GSA org codes

### ISSUE THREAD

**Issue by mgwalker** [18F/charlie#450]
The Q-expander actually tries to expand *every* GSA org code. @geekygirlsarah has taken the lead on getting those org codes from GSA periodically and updating the Q-expander accordingly. We should write down how she does that so she doesn't have to be the only person who does it. Or so when she wins the lottery and leaves us in the dust, we can still do it.

(See #449 for a taste of what the process looks like.)

**Comment by geekygirlsarah** [comment]
Have a good suggestion on where this should live?

**Comment by mgwalker** [comment]
What do you think about [the dev wiki](https://github.com/18F/charlie/wiki)? Updating these codes doesn't seem like it *has* to be a dev task, but I imagine it'll stay a dev task.

**Comment by geekygirlsarah** [comment]
Sounds good to me!

**Comment by geekygirlsarah** [comment]
I created https://github.com/18F/charlie/wiki/QexEdit. I'm open to edits or missing steps or better processes or whatever!
