### ISSUE TITLE
US Code "See Text" expansions are broken

### ISSUE THREAD

**Issue by adunkman** [18F/charlie#539]
See the screenshot below showing an app error when clicking on See Text: 

<img width="440" alt="image" src="https://github.com/18F/charlie/assets/14930/ad5bf95e-d6af-44c7-a050-d8712c79f2ba">

**Comment by mgwalker** [comment]
The returned text can sometimes be very long. Previously Slack automatically split those into multiple posts, but it looks like they now strictly enforce a 3,000-character limit and do not automatically split anything up. So we're gonna have to do some splitting.

**Comment by adunkman** [comment]
Confirmed fixed [on the reported message](https://gsa-tts.slack.com/archives/C03EPJGA6/p1717606465034299?thread_ts=1717534979.198949&cid=C03EPJGA6)! Thanks!
